let arrayOfClasses = [];

arrayOfClasses = [
  {
    id: 0,
    img: "/IMG/class-maths.jpg",
    subject: "Maths",
    location: "York",
    price: 5,
    spaces: 5,
  },
  {
    id: 1,
    img: "/IMG/history.png",
    subject: "History",
    location: "London",
    price: 100,
    spaces: 5,
  },
  {
    id: 2,
    img: "/IMG/class-maths.jpg",
    subject: "Maths",
    location: "Watford",
    price: 54,
    spaces: 5,
  },
  {
    id: 3,
    img: "/IMG/science.png",
    subject: "Science",
    location: "York",
    price: 84,
    spaces: 5,
  },
  {
    id: 4,
    img: "/IMG/art.png",
    subject: "Art",
    location: "Manchester",
    price: 10,
    spaces: 5,
  },
  {
    id: 5,
    img: "/IMG/science.png",
    subject: "Science",
    location: "Bristol",
    price: 68,
    spaces: 5,
  },
  {
    id: 6,
    img: "/IMG/art.png",
    subject: "Art",
    location: "Oxford",
    price: 32,
    spaces: 5,
  },
  {
    id: 7,
    img: "/IMG/class-maths.jpg",
    subject: "Maths",
    location: "Lincoln",
    price: 99,
    spaces: 5,
  },
  {
    id: 8,
    img: "/IMG/history.png",
    subject: "History",
    location: "Newcastle",
    price: 15,
    spaces: 5,
  },
  {
    id: 9,
    img: "/IMG/class-maths.jpg",
    subject: "Maths",
    location: "Liverpool",
    price: 49,
    spaces: 5,
  },
];
