let webStore = new Vue({
  el: "#app",
  data: {
    title: "Lessons to buy",
    classes: [
      {
        img: "/IMG/class-maths.jpg",
        subject: "Maths",
        location: "London",
        price: 100,
        spaces: 5,
      },
      {
        img: "/IMG/class-maths.jpg",
        subject: "Maths",
        location: "Oxford",
        price: 100,
        spaces: 5,
      },
      {
        img: "class-1",
        subject: "Maths",
        location: "London",
        price: 10,
        spaces: 5,
      },
      {
        img: "class-1",
        subject: "Maths",
        location: "London",
        price: 10,
        spaces: 5,
      },
      {
        img: "class-1",
        subject: "Maths",
        location: "London",
        price: 10,
        spaces: 5,
      },
      {
        img: "class-1",
        subject: "Maths",
        location: "London",
        price: 10,
        spaces: 5,
      },
      {
        img: "class-1",
        subject: "Maths",
        location: "London",
        price: 10,
        spaces: 5,
      },
      {
        img: "class-1",
        subject: "Maths",
        location: "London",
        price: 10,
        spaces: 5,
      },
      {
        img: "class-1",
        subject: "Maths",
        location: "London",
        price: 10,
        spaces: 5,
      },
      {
        img: "class-1",
        subject: "Maths",
        location: "London",
        price: 10,
        spaces: 5,
      },
    ],
  },
});
